# host
#http://localhost:3000/
http://localhost:3000/v1/api/
#https://httpbin.org:443


--silent
--include
--insecure

#Header-Name: Header-Value
# Authorization: Token
#headers
Accept: application/json
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# Qery
#GET /user

# Post
POST /shop/signup

{
  "email":"hungnk@gmail.com",
  "name": "hungnk",
  "password": "123456"
}
